name: mohamed_alqadi_education
description: برنامج محمد القاضي التعليمي العلمي
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.4
  uuid: ^4.5.0
  file_picker: ^8.1.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/teacher_mohamed_alqadi.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/teacher_mohamed_alqadi.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/teacher_mohamed_alqadi.png"
